### ISSUE TITLE
All plug-ins - only create error log when writting to it

### ISSUE THREAD

**Issue by liamellexus** [ellexus/mistral_plugins#112]
**Goal:** 

Only create error log if there are any error messages. The empty log files being created by every job/host is unnecessary file system usage and requires permissions to do this.

**Comment by gstarovic** [comment]
One way to do this: at mistral_startup time don't  create/open error_log file, just save the error_file and mode in the plugin struct. Then in the mistral_err check if error_log is still NULL and if it is then do what is now done at mistral_startup time.
This would avoid empty error log files.

**Comment by gstarovic** [comment]
done
