### ISSUE TITLE
The Mistral Elasticsearch plugin does not run inside Singularity containers

### ISSUE THREAD

**Issue by ddumitre456** [ellexus/mistral_plugins#73]
**Goal:** 

The Mistral Elasticsearch plugin does not run inside Singularity containers because two shared libraries are missing from `mistral_elasticsearch` binary.

The two missing libraries are:

`libkrb5support.so.0`
`libkeyutils.so`

**Solution:** 

The solution is two link statically the respective libraries.

**Comment by liamellexus** [comment]
Fixed in #74
