### ISSUE TITLE
Asserts in plugin_control.c are not helpful

### ISSUE THREAD

**Issue by RichardSJordan** [ellexus/mistral_plugins#77]
**Goal:** Keep plugins operating even if they encounter problems

Some of the functions in plugin_control.c use `assert`s. If the code was changed to handle the unexpected behaviour, the plugin may be able to recover from whatever has happened. If nothing else, it would give us a chance to log some information to help debug the situation.

https://github.com/ellexus/breeze-repo/issues/3972

**Comment by liamellexus** [comment]
Fixed in #78
